SELECT 
    GSO_PRODUCT_PARAM.CNTRY_CD AS CNTRY_CD,
    GSO_PRODUCT_PARAM.DIALECT_NM AS DIALECT_NM,
    GSO_PRODUCT_PARAM.GRP_PRPS_CD_GLBL__C AS GRP_PRPS_CD_GLBL__C
FROM 
    gs_edb_cms.GSO_PRODUCT_PARAM;
