SELECT 
    END_DT AS END_DT,
    CEASE_PBLSH_DT AS CEASE_PBLSH_DT,
    PROD_GRP_ID AS PROD_GRP_ID,
    DIALECT_NM AS DIALECT_NM,
    CNTRY_CD AS CNTRY_CD
FROM 
    gs_edb_cms.MTM_GH_PROD_GRP_TRNSLTNS_VW;