SELECT 
    TRNSLTD_DSPLY_NM AS TRNSLTD_DSPLY_NM,
    TRNSLTD_PROD_DESC_TXT AS TRNSLTD_PROD_DESC_TXT,
    DIALECT_NM AS DIALECT_NM,
    CNTRY_CD AS CNTRY_CD,
    CEASE_PBLSH_DT AS CEASE_PBLSH_DT,
    START_DT AS START_DT,
    END_DT AS END_DT,
    PROD_ID AS PROD_ID
FROM 
    gs_edb_cms.MTM_GH_PROD_TRNSLTNS_VW;