SELECT 
    PRD.BRND_CD AS BRND_CD, 
    PRD.COLLAB_IND AS COLLAB_IND, 
    PRD.CRT_DT AS CRT_DT, 
    PRD.DMND_DFLT_CNVRSN_FCTR AS DMND_DFLT_CNVRSN_FCTR, 
    PRD.DMND_DFLT_CNVRSN_UOM_CD AS DMND_DFLT_CNVRSN_UOM_CD, 
    PRD.DMND_DSG_PTNCY_UOM_CD AS DMND_DSG_PTNCY_UOM_CD, 
    PRD.DMND_PKG_CNTNT_PRSNTN_ABBR_CD AS DMND_PKG_CNTNT_PRSNTN_ABBR_CD, 
    PRD.DMND_PKG_CNTNT_QTY AS DMND_PKG_CNTNT_QTY, 
    PRD.DMND_PKG_CNTNT_UOM_CD AS DMND_PKG_CNTNT_UOM_CD, 
    PRD.DMND_PKG_QTY AS DMND_PKG_QTY, 
    PRD.DMND_PKG_TYP_CD AS DMND_PKG_TYP_CD, 
    PRD.DMND_PKG_UOM_CD AS DMND_PKG_UOM_CD, 
    PRD.DMND_PTNCY_DSG_QTY AS DMND_PTNCY_DSG_QTY, 
    PRD.DMND_PTNCY_QTY AS DMND_PTNCY_QTY, 
    PRD.DMND_QTY_PTNCY_UOM_CD AS DMND_QTY_PTNCY_UOM_CD, 
    PRD.DMND_SALABLE_IND AS DMND_SALABLE_IND, 
    PRD.DSG_FREQ_CD AS DSG_FREQ_CD, 
    PRD.EDCTNL_MTRL_ID AS EDCTNL_MTRL_ID, 
    PRD.EDP_FMLY_CD AS EDP_FMLY_CD, 
    PRD.EDP_PKG_SIZE_CD AS EDP_PKG_SIZE_CD, 
    PRD.EDP_PROD_CD AS EDP_PROD_CD, 
    PRD.END_DT AS END_DT, 
    PRD.FDA_PKG_SIZE_CD AS FDA_PKG_SIZE_CD, 
    PRD.ITEM_RGLTRY_SCHED_CD AS ITEM_RGLTRY_SCHED_CD, 
    PRD.LBL_CD AS LBL_CD, 
    PRD.LST_LOT_EXPRTN_DT AS LST_LOT_EXPRTN_DT, 
    PRD.MTRL_NBR AS MTRL_NBR, 
    PRD.NBR_OF_DOSES AS NBR_OF_DOSES, 
    PRD.PROD_ID AS PROD_ID, 
    PRD.PROD_NM AS PROD_NM, 
    PRD.PROD_TYP AS PROD_TYP, 
    PRD.PRSCPTN_PROD_CD AS PRSCPTN_PROD_CD, 
    PRD.RPKG_CD AS RPKG_CD, 
    PRD.SHPMNT_MULTI AS SHPMNT_MULTI, 
    PRD.SRC_CD AS SRC_CD, 
    PRD.START_DT AS START_DT, 
    PRD.STD_DOT_CNVRSN_FCTR AS STD_DOT_CNVRSN_FCTR, 
    PRD.TRD_NM_ID AS TRD_NM_ID, 
    PRD.UPDT_DT AS UPDT_DT, 
    PRD.LST_PBLSH_DT AS LST_PBLSH_DT, 
    PRD.CEASE_PBLSH_DT AS CEASE_PBLSH_DT, 
    PRD.EDCTNL_MTRL_ITM_TYP AS EDCTNL_MTRL_ITM_TYP, 
    PRD.PROD_DISEASE_ST_FLG AS PROD_DISEASE_ST_FLG, 
    PRD.REFRIG_CD AS REFRIG_CD, 
    PRD.TRACKABLE_ITEM AS TRACKABLE_ITEM, 
    STGH_PRD.PROD_GRP_ID_PRNT AS PROD_GRP_PRNT_ID, 
    ALT_PRD.CNTRY_CD AS ALT_CNTRY_CD, 
    STGH_PRD.GRP_PRPS_CD AS GRP_PRPS_CD, 
    MAX_PRD.END_DT AS END_DT_PROD_GRP_PROD, 
    MAX_PRD.CEASE_PBLSH_DT AS CEASE_PBLSH_DT_PROD_GRP_PROD, 
    STGH_PRD.CNTRY_CD AS STGH_CNTRY_CD
FROM (
    SELECT 
        BRND_CD, COLLAB_IND, CRT_DT, DMND_DFLT_CNVRSN_FCTR, DMND_DFLT_CNVRSN_UOM_CD,
        DMND_DSG_PTNCY_UOM_CD, DMND_PKG_CNTNT_PRSNTN_ABBR_CD, DMND_PKG_CNTNT_QTY, 
        DMND_PKG_CNTNT_UOM_CD, DMND_PKG_QTY, DMND_PKG_TYP_CD, DMND_PKG_UOM_CD, 
        DMND_PTNCY_DSG_QTY, DMND_PTNCY_QTY, DMND_QTY_PTNCY_UOM_CD, DMND_SALABLE_IND, 
        DSG_FREQ_CD, EDCTNL_MTRL_ID, EDP_FMLY_CD, EDP_PKG_SIZE_CD, EDP_PROD_CD, 
        END_DT, FDA_PKG_SIZE_CD, ITEM_RGLTRY_SCHED_CD, LBL_CD, LST_LOT_EXPRTN_DT, 
        MTRL_NBR, NBR_OF_DOSES, PROD_ID, PROD_NM, PROD_TYP, PRSCPTN_PROD_CD, 
        RPKG_CD, SHPMNT_MULTI, SRC_CD, START_DT, STD_DOT_CNVRSN_FCTR, TRD_NM_ID, 
        UPDT_DT, LST_PBLSH_DT, CEASE_PBLSH_DT, EDCTNL_MTRL_ITM_TYP, PROD_DISEASE_ST_FLG, 
        REFRIG_CD, TRACKABLE_ITEM
    FROM gs_edb_cms.MTM_GH_PROD_VW
) PRD
JOIN (
    SELECT DISTINCT
        A.PROD_ID, B.PROD_GRP_ID, B.GRP_PRPS_CD, C.END_DT,
        MAX(CASE WHEN C.CEASE_PBLSH_DT IS NULL 
                 THEN DATE '9999-12-31' 
                 ELSE C.CEASE_PBLSH_DT 
            END) AS CEASE_PBLSH_DT,
        MAX(C.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM gs_edb_cms.MTM_GH_PROD_VW A
    JOIN gs_edb_cms.MTM_GH_PROD_GRP_TO_PROD_VW C 
      ON A.PROD_ID = C.PROD_CHILD_ID
    JOIN gs_edb_cms.MTM_GH_PROD_GRP_VW B 
      ON B.PROD_GRP_ID = C.PROD_GRP_PRNT_ID
    GROUP BY A.PROD_ID, B.PROD_GRP_ID, B.GRP_PRPS_CD, C.END_DT
) MAX_PRD ON PRD.PROD_ID = MAX_PRD.PROD_ID
JOIN (
    SELECT DISTINCT
        A.PROD_ID, B.CNTRY_CD, MAX(B.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM gs_edb_cms.MTM_GH_PROD_VW A
    JOIN gs_edb_cms.MTM_GH_PROD_ALTRNT_ID_VW B 
      ON A.PROD_ID = B.PROD_ID
    GROUP BY A.PROD_ID, B.CNTRY_CD
) ALT_PRD ON PRD.PROD_ID = ALT_PRD.PROD_ID
JOIN (
    SELECT DISTINCT
        A.PROD_ID, B.CNTRY_CD, MAX(B.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM gs_edb_cms.MTM_GH_PROD_VW A
    JOIN gs_edb_cms.MTM_GH_PROD_TRNSLTNS_VW B 
      ON A.PROD_ID = B.PROD_ID
    GROUP BY A.PROD_ID, B.CNTRY_CD
) TRNS_PRD ON PRD.PROD_ID = TRNS_PRD.PROD_ID
JOIN (
    SELECT DISTINCT
        A.PROD_GRP_ID_CHILD, A.PROD_GRP_ID_PRNT, C.GRP_PRPS_CD, A.CNTRY_CD
    FROM gs_edb_cms.MTM_GH_PG_TO_PG_VW A
    JOIN gs_edb_cms.MTM_GH_PROD_GRP_VW B 
      ON A.PROD_GRP_ID_CHILD = B.PROD_GRP_ID AND B.GRP_PRPS_CD = 'STGH'
    JOIN gs_edb_cms.MTM_GH_PROD_GRP_VW C 
      ON A.PROD_GRP_ID_PRNT = C.PROD_GRP_ID AND C.GRP_PRPS_CD IN ('MKTP')
) STGH_PRD ON MAX_PRD.PROD_GRP_ID = STGH_PRD.PROD_GRP_ID_CHILD
WHERE PRD.PROD_TYP IN ('COMPETITOR', 'LILLY')
  AND ALT_PRD.CNTRY_CD = TRNS_PRD.CNTRY_CD
  AND (ALT_PRD.LST_PBLSH_DT > active_prod_date 
       OR TRNS_PRD.LST_PBLSH_DT > active_prod_date 
       OR PRD.LST_PBLSH_DT > active_prod_date 
       OR MAX_PRD.LST_PBLSH_DT > active_prod_date);
