SELECT 
    PRD.BRND_CD, 
    PRD.COLLAB_IND, 
    PRD.CRT_DT, 
    PRD.DMND_DFLT_CNVRSN_FCTR, 
    PRD.DMND_DFLT_CNVRSN_UOM_CD, 
    PRD.DMND_DSG_PTNCY_UOM_CD, 
    PRD.DMND_PKG_CNTNT_PRSNTN_ABBR_CD, 
    PRD.DMND_PKG_CNTNT_QTY, 
    PRD.DMND_PKG_CNTNT_UOM_CD, 
    PRD.DMND_PKG_QTY, 
    PRD.DMND_PKG_TYP_CD, 
    PRD.DMND_PKG_UOM_CD, 
    PRD.DMND_PTNCY_DSG_QTY, 
    PRD.DMND_PTNCY_QTY, 
    PRD.DMND_QTY_PTNCY_UOM_CD, 
    PRD.DMND_SALABLE_IND, 
    PRD.DSG_FREQ_CD, 
    PRD.EDCTNL_MTRL_ID, 
    PRD.EDP_FMLY_CD, 
    PRD.EDP_PKG_SIZE_CD, 
    PRD.EDP_PROD_CD, 
    PRD.END_DT, 
    PRD.FDA_PKG_SIZE_CD, 
    PRD.ITEM_RGLTRY_SCHED_CD, 
    PRD.LBL_CD, 
    PRD.LST_LOT_EXPRTN_DT, 
    PRD.MTRL_NBR, 
    PRD.NBR_OF_DOSES, 
    PRD.PROD_ID, 
    PRD.PROD_NM, 
    PRD.PROD_TYP, 
    PRD.PRSCPTN_PROD_CD, 
    PRD.RPKG_CD, 
    PRD.SHPMNT_MULTI, 
    PRD.SRC_CD, 
    PRD.START_DT, 
    PRD.STD_DOT_CNVRSN_FCTR, 
    PRD.TRD_NM_ID, 
    PRD.UPDT_DT, 
    PRD.LST_PBLSH_DT, 
    PRD.CEASE_PBLSH_DT, 
    PRD.EDCTNL_MTRL_ITM_TYP, 
    PRD.PROD_DISEASE_ST_FLG, 
    PRD.REFRIG_CD, 
    PRD.TRACKABLE_ITEM, 
    STGH_PRD.PROD_GRP_ID_PRNT AS PROD_GRP_PRNT_ID, 
    TRNS_PRD.CNTRY_CD AS PROD_TRNS_CNTRY_CD, 
    STGH_PRD.GRP_PRPS_CD, 
    MAX_PRD.END_DT AS END_DT_PROD_GRP_PROD, 
    MAX_PRD.CEASE_PBLSH_DT AS CEASE_PBLSH_DT_PROD_GRP_PROD, 
    TRNS_PG.CNTRY_CD AS PG_TRNS_CNTRY_CD
FROM (
    SELECT 
        BRND_CD, COLLAB_IND, CRT_DT, DMND_DFLT_CNVRSN_FCTR, DMND_DFLT_CNVRSN_UOM_CD,
        DMND_DSG_PTNCY_UOM_CD, DMND_PKG_CNTNT_PRSNTN_ABBR_CD, DMND_PKG_CNTNT_QTY, 
        DMND_PKG_CNTNT_UOM_CD, DMND_PKG_QTY, DMND_PKG_TYP_CD, DMND_PKG_UOM_CD, 
        DMND_PTNCY_DSG_QTY, DMND_PTNCY_QTY, DMND_QTY_PTNCY_UOM_CD, DMND_SALABLE_IND, 
        DSG_FREQ_CD, EDCTNL_MTRL_ID, EDP_FMLY_CD, EDP_PKG_SIZE_CD, EDP_PROD_CD, 
        END_DT, FDA_PKG_SIZE_CD, ITEM_RGLTRY_SCHED_CD, LBL_CD, LST_LOT_EXPRTN_DT, 
        MTRL_NBR, NBR_OF_DOSES, PROD_ID, PROD_NM, PROD_TYP, PRSCPTN_PROD_CD, 
        RPKG_CD, SHPMNT_MULTI, SRC_CD, START_DT, STD_DOT_CNVRSN_FCTR, TRD_NM_ID, 
        UPDT_DT, LST_PBLSH_DT, CEASE_PBLSH_DT, EDCTNL_MTRL_ITM_TYP, PROD_DISEASE_ST_FLG, 
        REFRIG_CD, TRACKABLE_ITEM
    FROM 
        gs_edb_cms.MTM_GH_PROD_VW
) PRD
JOIN (
    SELECT DISTINCT
        A.PROD_ID, 
        B.PROD_GRP_ID, 
        B.GRP_PRPS_CD, 
        C.END_DT,
        MAX(
            CASE WHEN C.CEASE_PBLSH_DT IS NULL 
                 THEN DATE '9999-12-31' 
                 ELSE C.CEASE_PBLSH_DT 
            END
        ) AS CEASE_PBLSH_DT,
        MAX(C.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM 
        gs_edb_cms.MTM_GH_PROD_VW A
    JOIN 
        gs_edb_cms.MTM_GH_PROD_GRP_TO_PROD_VW C 
        ON A.PROD_ID = C.PROD_CHILD_ID
    JOIN 
        gs_edb_cms.MTM_GH_PROD_GRP_VW B 
        ON B.PROD_GRP_ID = C.PROD_GRP_PRNT_ID
    GROUP BY 
        A.PROD_ID, B.PROD_GRP_ID, B.GRP_PRPS_CD, C.END_DT
) MAX_PRD ON PRD.PROD_ID = MAX_PRD.PROD_ID
JOIN (
    SELECT DISTINCT
        A.PROD_GRP_ID_CHILD, 
        A.PROD_GRP_ID_PRNT, 
        C.GRP_PRPS_CD
    FROM 
        gs_edb_cms.MTM_GH_PG_TO_PG_VW A
    JOIN 
        gs_edb_cms.MTM_GH_PROD_GRP_VW B 
        ON A.PROD_GRP_ID_CHILD = B.PROD_GRP_ID 
        AND B.GRP_PRPS_CD = 'STGH'
    JOIN 
        gs_edb_cms.MTM_GH_PROD_GRP_VW C 
        ON A.PROD_GRP_ID_PRNT = C.PROD_GRP_ID 
        AND C.GRP_PRPS_CD IN ('BRND')
) STGH_PRD ON MAX_PRD.PROD_GRP_ID = STGH_PRD.PROD_GRP_ID_CHILD
JOIN (
    SELECT
        B.PROD_GRP_ID, 
        B.CNTRY_CD, 
        B.dialect_nm, 
        MAX(B.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM 
        gs_edb_cms.MTM_GH_PROD_GRP_TRNSLTNS_VW B
    JOIN 
        gs_edb_cms.MTM_GH_PROD_GRP_VW A 
        ON A.PROD_GRP_ID = B.PROD_GRP_ID
    WHERE 
        A.GRP_PRPS_CD = 'BRND'
    GROUP BY 
        B.PROD_GRP_ID, B.CNTRY_CD, B.dialect_nm
) TRNS_PG ON TRNS_PG.PROD_GRP_ID = STGH_PRD.PROD_GRP_ID_PRNT
JOIN (
    SELECT DISTINCT
        A.PROD_ID, 
        B.CNTRY_CD, 
        MAX(B.LST_PBLSH_DT) AS LST_PBLSH_DT
    FROM 
        gs_edb_cms.MTM_GH_PROD_VW A
    JOIN 
        gs_edb_cms.MTM_GH_PROD_TRNSLTNS_VW B 
        ON A.PROD_ID = B.PROD_ID
    GROUP BY 
        A.PROD_ID, B.CNTRY_CD
) TRNS_PRD ON PRD.PROD_ID = TRNS_PRD.PROD_ID
WHERE 
    PRD.PROD_TYP IN ('COMPETITOR', 'LILLY')
    AND (
        TRNS_PRD.LST_PBLSH_DT > active_prod_date
        OR PRD.LST_PBLSH_DT > active_prod_date
        OR MAX_PRD.LST_PBLSH_DT > active_prod_date
        OR TRNS_PG.LST_PBLSH_DT > active_prod_date
    );
